### ISSUE TITLE
No module named 'mprop' when running on MacOS with docker

### ISSUE THREAD

**Issue by cBevilaqua** [jupyter-naas/naas#280]
I just cloned the main branch and tried to run Naas with docker, using the command "docker-compose up" or simply "make" and this is the output of my terminal:
`Starting naas runner on port 5000.
naas_1  | Traceback (most recent call last):
naas_1  |   File "/opt/conda/lib/python3.8/runpy.py", line 185, in _run_module_as_main
naas_1  |     mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
naas_1  |   File "/opt/conda/lib/python3.8/runpy.py", line 111, in _get_module_details
naas_1  |     __import__(pkg_name)
naas_1  |   File "/home/ftp/naas/naas/__init__.py", line 6, in <module>
naas_1  |     from .runner.notifications import Notifications
naas_1  |   File "/home/ftp/naas/naas/runner/__init__.py", line 1, in <module>
naas_1  |     from .runner import Runner  # noqa: F401
naas_1  |   File "/home/ftp/naas/naas/runner/runner.py", line 5, in <module>
naas_1  |     from .controllers.auth import AuthController
naas_1  |   File "/home/ftp/naas/naas/runner/controllers/auth.py", line 2, in <module>
naas_1  |     from naas_drivers import naasauth
naas_1  |   File "/home/ftp/drivers/naas_drivers/__init__.py", line 3, in <module>
naas_1  |     from mprop import mproperty
naas_1  | ModuleNotFoundError: No module named 'mprop'
naas_1  | Naas Runner exited !`

Thanks!

**Comment by cBevilaqua** [comment]
solved by adding the module mprop to setup.py
